name: Deploy JAR to deploy branch

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Get JAR file name
      id: jar-name
      run: |
        JAR_FILE=$(find target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "jar_name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT

    - name: Create and checkout deploy branch
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git fetch origin deploy:deploy 2>/dev/null || git checkout -b deploy
        git checkout deploy

    - name: Copy JAR and commit
      run: |
        cp ${{ steps.jar-name.outputs.jar_file }} .
        git add ${{ steps.jar-name.outputs.jar_name }}
        git commit -m "Auto-deploy: ${{ steps.jar-name.outputs.jar_name }} from ${{ github.sha }}" || echo "No changes to commit"

    - name: Push to deploy branch
      run: git push origin deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
